name: Minishell Build and Publish

on:
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    name: Publish binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Fix Readline on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install readline
        brew link --force readline
        cpan Term::ReadLine::Gnu
        brew unlink readline
        export LIBRARY_PATH="/usr/local/opt/readline/lib:$LIBRARY_PATH"
        export CPATH="/usr/local/opt/readline/include:$CPATH"
    - name: Build
      run: make all
    - name: Rename minishell ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
          mv minishell minishell-linux
          asset_name="minishell-linux"
          echo "ASSET_NAME=$asset_name" >> $GITHUB_ENV
    - name: Rename minishell macOS
      if: matrix.os == 'macos-latest'
      run: |
          mv minishell minishell-macos
          asset_name="minishell-macos"
          echo "ASSET_NAME=$asset_name" >> $GITHUB_ENV
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.RELEASE_TOKEN }}
        file: ${{ env.ASSET_NAME }}
        asset_name: ${{ env.ASSET_NAME }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest minishell master release"
