name: Minishell Build and Publish to Linux

on:
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make all
    - name: Rename minishell
      run: |
          mv minishell minishell-linux
          asset_name="minishell-linux"
          echo "ASSET_NAME=$asset_name" >> $GITHUB_ENV
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.RELEASE_TOKEN }}
        file: ${{ env.ASSET_NAME }}
        asset_name: ${{ env.ASSET_NAME }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest minishell master release"
